# ~/Documents/cyberchallenge/zshconfig/gitconfig_global

[core]
        autocrlf = input
        editor = nano

[color]
    ui = auto

[init]
    defaultBranch = main

[alias]
        statuss = status -b
        br = branch
        check = checkout
        lg = log --color --graph --all --abbrev-commit --stat --pretty=format:'%C(yellow)%h%Creset %C(green)%<(13,trunc)%cr%Creset %C(bold blue)%<(16,trunc)%an%Creset %s%C(auto)%d'
        addcomm = commit -am
        errcommit = commit --amend -m
        erradd = restore --staged

