#!/usr/bin/env python3
"""
gen_requirements.py — regenerate the repo-root requirements.txt as the UNION of
every other requirements.txt in the project.

It is run automatically by:
  - the git pre-commit hook (.githooks/pre-commit), so a commit that touches any
    sub-requirements.txt re-syncs the root file, and
  - auto.sh, so the root file is fresh every time you run the toolkit.

Dedup is by package name (case-insensitive); the first spec seen for a name wins.
"""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "requirements.txt")
SKIP_DIRS = {".git", "__pycache__", "venv", ".venv", "build", "node_modules"}
_SPLIT = re.compile(r"[<>=!~;\[\s]")


def iter_req_files():
    for dirpath, dirnames, filenames in os.walk(ROOT):
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
        if "requirements.txt" not in filenames:
            continue
        full = os.path.join(dirpath, "requirements.txt")
        if os.path.abspath(full) == os.path.abspath(OUT):
            continue  # never read our own output back in
        yield full


def pkg_name(spec):
    return _SPLIT.split(spec, 1)[0].strip().lower()


def main():
    seen = {}  # name -> first full spec line
    for f in sorted(iter_req_files()):
        with open(f) as fh:
            for line in fh:
                line = line.split("#", 1)[0].strip()  # drop comments / blanks
                if not line:
                    continue
                name = pkg_name(line)
                if name and name not in seen:
                    seen[name] = line

    lines = [seen[k] for k in sorted(seen)]
    with open(OUT, "w") as fh:
        fh.write("# AUTO-GENERATED — do not edit by hand.\n")
        fh.write("# Union of every other requirements.txt in this repo, regenerated by\n")
        fh.write("# scripts/gen_requirements.py (via the .githooks/pre-commit hook and auto.sh).\n")
        fh.write("# Install every Python exploit dependency at once:\n")
        fh.write("#   pip install -r requirements.txt\n")
        fh.write("# (ExploitFarm's server is separate — https://github.com/Pwnzer0tt1/exploitfarm)\n")
        for line in lines:
            fh.write(line + "\n")
    print(f"[gen_requirements] wrote {OUT} ({len(lines)} packages)")


if __name__ == "__main__":
    main()
